# Generated by Django 4.2.4 on 2024-02-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soildata',
            old_name='nitrogen',
            new_name='ldr',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='grid_section',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='potassium',
        ),
    ]
